apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: spring-app
spec:
  provider: azure

  parameters:
    keyvaultName: my-keyvault
    tenantId: <tenant-id>

    objects: |
      array:
        - |
          objectName: db-url
          objectType: secret
        - |
          objectName: db-username
          objectType: secret
        - |
          objectName: db-password
          objectType: secret

  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: db-url
          key: SPRING_DATASOURCE_URL
        - objectName: db-username
          key: SPRING_DATASOURCE_USERNAME
        - objectName: db-password
          key: SPRING_DATASOURCE_PASSWORD